apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hauzral-api-ingress
  namespace: hauzral
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/limit-rpm: "60"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.hauzral.com
        - hauzral.com
      secretName: hauzral-tls
  rules:
    - host: api.hauzral.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hauzral-api
                port:
                  number: 8000
    - host: hauzral.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hauzral-api
                port:
                  number: 8000
